#************************* makefile for messages **************************
#
#######################	dependencies begin here. #########################

all: $(COUNTRY).idx

$(COUNTRY).idx: $(COUNTRY).msg

